### ISSUE TITLE
Audio "skips & buffers" if stream is re-started [ ShoutCast ] with flash fallback

### ISSUE THREAD

**Issue by darkyen** [jplayer/jPlayer#137]
The simple example 

http://jsfiddle.net/esS59/

on firefox starts to skip and buffer if the stream is restarted , which on chrome it plays it seemlessly with no audible differences even if the source is changed.

I wonder if thats with the flash fallback ?

**Comment by GinoPino88** [comment]
Hi, I've the same problem with the jPlayer i've made for my radio station, but I don't find the solution, @darkyen, can you explain how to fix that?

Thanks so much
