### ISSUE TITLE
Strange issue with jPlayer (Playlist) not initialized / ready with jQuery's $.each() on FF/Webkit, IE works?!?

### ISSUE THREAD

**Issue by exside** [jplayer/jPlayer#159]
I was really digging into this in the last days but just cannot find any solution or workaround to this, so I thought maybe this is just not possible like I thought it was or something very strange is happening and somebody else does know what to do =)...

You can check the live site out at www.radiobern1.ch, then watch for the black audio module on the right and click "Nachhören", there should be a list of jPlayers with playlists (every player has a playlist with the last 10 audios of that category), hopefully all of them playable...if not, you're seeing the same problem as I do (try with latest Firefox or Safari maybe Chrome...I use Iron, but should be the same)...

In IE9 all the players are always loaded and playable (playlists are expanded somehow, didn't find time to get that issue, but it doesn't have an effect when I do this by purpose for all browsers, so the playlists are expanded everywhere), in my observations that's not the case in Firefox and Webkit browsers, there it can look like this (Firefox 20.0, OSX Lion, loacl)

![bildschirmfoto 2013-05-03 um 23 07 49](https://f.cloud.github.com/assets/445501/461354/de6100a4-b437-11e2-8d20-6b4189c6b4e3.png)

or like this (Firefox 19, OSX Lion, Browserstack)

![bildschirmfoto 2013-05-03 um 23 31 47](https://f.cloud.github.com/assets/445501/461395/f7f73f32-b438-11e2-9d17-6d553cadd5df.png)

even worse (Firefox 17, OSX Lion, Browserstack)

![bildschirmfoto 2013-05-04 um 00 12 18](https://f.cloud.github.com/assets/445501/461564/b6f99ca4-b43e-11e2-9a16-9463d8cde7b3.png)

or like this (Iron 23 = chrome 23, OSX local)

![bildschirmfoto 2013-05-03 um 23 08 33](https://f.cloud.github.com/assets/445501/461359/f377f2f4-b437-11e2-969e-3bc8596d9483.png)

or also like this (Safari 6, OSX, Browserstack), loaded completely...sometimes

![bildschirmfoto 2013-05-03 um 23 30 01](https://f.cloud.github.com/assets/445501/461401/279f0e86-b439-11e2-8b7c-55e02b180ef3.png)

It's not about my computer, I tested on at least 3 other ones and have the same issue. In a quick test with windows on browserstack (don't have a windows machine on my own, where I'm allowed to install something =D) I couldn't reproduce the same thing with the same browsers^^...so maybe an OSX issue?

what I'm doing javascript wise there is the following:

``` javascript
    // AUDIO
    $(window).load( function() {
        $('#podcasts .player').each(function(i) {
            //$(this).delay(1000*i).fadeTo(0, 1, function() {
                var ready = false;
                var player = $(this);
                var playercontainer = player;
                var playerid = player.attr('id');
                var nextplayer = player.nextAll('.player:first');

                var cssSelector = { jPlayer: '#' + playerid, cssSelectorAncestor: '.' + playerid }; // dynamically generating the player cssSelector
                //var playlist = data;
                var playlist = playercontainer.data('playlist'); // getting the json playlist from a data-attribute
                //console.log(playlist);
                var options = {
                    ready: function (event) {
                        ready = true;

                        console.log('ready');

                        // stripped unimportant stuff

                        // rebind normal click behaviour to rss icon, doesn't react somehow when not done like this...trying to find out why
                        $(this).next().find('.jp-rss').bind('click', function(e) {
                            window.open($(this).attr('href'), '_blank');
                        });

                        // stripped slider handling stuff
                    },
                    play: function(event) { // To avoid jPlayers playing together.
                        $(this).jPlayer("pauseOthers");
                        // stripped other stuff
                    },
                    timeupdate: function(event) {
                        // stripped, handling slider and other ui stuff
                    },
                    pause: function(event) {
                        // stripped, class manipulations
                    },
                    progress: function(event) {
                        // stripped, just updating the progress stuff
                    },
                    ended: function(event) {
                        // stripped, unimportant, just adding/removing some classes
                    },
                    repeat: function(event) { 
                        // nothing
                    },
                    error: function(event) {
                        if(ready && event.jPlayer.error.type === $.jPlayer.error.URL_NOT_SET) {
                            podcast.next();
                        }
                    },
                    playlistOptions: {
                        // none
                    },
                    solution: 'html, flash',
                    swfPath: "assets/site/flash",
                    wmode: "window",
                    supplied: "mp3",
                    volume: 1,
                    muted: 0,
                    preload: 'metadata',
                    backgroundColor: '#000000'
                };

                var podcast = new jPlayerPlaylist(cssSelector, playlist, options);
            //});
        });
    });
```

for details about the html markup see the page itself or here: https://github.com/happyworm/jPlayer/issues/155

so what I guess is the problem is the .each(function() { }); part (so basically everything =D), it seems as it is too fast or something like that, but I'm absolutely not sure because it DOES WORK sometimes...when I log the ready state to the console I only get it (when it doesnt load all players) for the players, that are actually working afterwards, for the rest it seems as they are not getting initialized...I went even into the playlist plugin code and logged there, it runs for each instance but it does not get initialized every time...

when I watch this in Firebug I can see the jPlayer object attached to the player (that doesn't get initialized)...so it does see and process it somehow, but doesn't finish it...

![bildschirmfoto 2013-05-03 um 23 45 54](https://f.cloud.github.com/assets/445501/461467/154c640c-b43b-11e2-91fa-d2ba18ef1850.png)

I'm really out of ideas where the problem could be (I even tried some very ugly things to delay the .each loops by funny things like $(this).delay(1000*i).fadeTo(0, 1, function() { });
as you can see commented out in the js above.)

So if somebody has any suggestions for another approach to do this (without having to invoke each single instance the "usual" way) or any suggestions what could be the problem, I would be sooo thankful =)...

this is maybe also related to:
https://github.com/happyworm/jPlayer/issues/85
https://github.com/happyworm/jPlayer/issues/88

**Comment by onigetoc** [comment]
Bye the way, your player don't work on Chrome
