### ISSUE TITLE
Can’t play multiple (11 items) mp3 jPlayers wrapped with WebView control (with Eclipse) in any Android devices

### ISSUE THREAD

**Issue by AngelTs** [jplayer/jPlayer#215]
Can’t play multiple (11 items) mp3 jPlayers wrapped with WebView control (with Eclipse) in any Android devices (tested with many devices in Emulator of Android SDK + some physical Android devices) => No one can play any mp3 file. The same code In any (Firefox, IE, Chrome) browsers works OK without a problems. Android Fix (jPlayerAndroidFix(...); [2.5.5]) also not working here!
Using jPlayer 2.6.0; jQuery v1.10.2; Windows 7 Ultimate SP1
//
//PLAYER #1
//
    $("#jquery_jplayer_1").jPlayer({
        ready: function () {
            $(this).jPlayer("setMedia", {
                //mp3:  'data:audio/mp3;base64,' + "....................."
                mp3:    'mp3/story 1.mp3'
            });
        },
        play: function() { // To avoid multiple jPlayers playing together.
            $(this).jPlayer("pauseOthers");
        },
        swfPath: "jPlayer",
        supplied: "mp3",
        cssSelectorAncestor: "#jp_container_1",
        wmode: "window",
        smoothPlayBar: true,
        keyEnabled: true
    });
//
//PLAYER #2
//
    $("#jquery_jplayer_2").jPlayer({
        ready: function () {
            $(this).jPlayer("setMedia", {
                //mp3:  'data:audio/mp3;base64,' + "....................."
                mp3:    'mp3/story 2.mp3'
            });
        },
        play: function() { // To avoid multiple jPlayers playing together.
            $(this).jPlayer("pauseOthers");
        },
        swfPath: "jPlayer",
        supplied: "mp3",
        cssSelectorAncestor: "#jp_container_2",
        wmode: "window",
        smoothPlayBar: true,
        keyEnabled: true
    });
//
//PLAYER #3
//
    $("#jquery_jplayer_3").jPlayer({
        ready: function () {
            $(this).jPlayer("setMedia", {
                //mp3:  'data:audio/mp3;base64,' + "....................."
                mp3:    'mp3/story 3.mp3'
            });
        },
        play: function() { // To avoid multiple jPlayers playing together.
            $(this).jPlayer("pauseOthers");
        },
        swfPath: "jPlayer",
        supplied: "mp3",
        cssSelectorAncestor: "#jp_container_3",
        wmode: "window",
        smoothPlayBar: true,
        keyEnabled: true
    });
...
...
...

**Comment by LeleDev** [comment]
If I add more than 10 players they don't work, what can I do?

**Comment by LeleDev** [comment]
P.S. it does happen also on desktop browsers (I'm using circle player)
