### ISSUE TITLE
jPlayer works on website, but not on iPad and iPhone :S

### ISSUE THREAD

**Issue by MichaelDeBoey** [jplayer/jPlayer#272]
Hello everyone!
Like the title said jPlayer works perfect on my website, but not on my iPad and iPhone (both iOS 8) :S
Is there anything I need to do especially for iOS-devices or...?
You can find my page [here](http://webplayer.babsradio.be).
I allready downloaded 2.9.1, but that doesn't help :S

**Comment by rasheshved** [comment]
Hii Can you guys pls say how to resolve this issue as i m facing the same issue.
