### ISSUE TITLE
jPlayer live stream doesn't work at Safari 11 on iOS 11.

### ISSUE THREAD

**Issue by ashum81** [jplayer/jPlayer#400]
This demo does not work: http://www.jplayer.org/latest/demo-08/

**Comment by ashum81** [comment]
I'm sorry. This link does not work cause "this radiostation is not available in your country" (Russia).
My problem with my stream on my website and iOS 11 was caused by error in Icecast server version 2.4.0-kh3. After update to current version 2.4.0-kh7 iOS 11 can play stream well.

**Comment by rocchidavide** [comment]
I also have problems with jPlayer and iOS, both on Safari and Chrome. I obtain Unhandled Promise Rejection [object DOMError]

**Comment by suijiaxin123** [comment]
> I also have problems with jPlayer and iOS, both on Safari and Chrome. I obtain Unhandled Promise Rejection [object DOMError]
Excuse me, i want to know how to slove the problem?
