### ISSUE TITLE
Feature Request: jPlayerPlaylist track lengths

### ISSUE THREAD

**Issue by Scottjutsu** [jplayer/jPlayer#58]
Mark, first of all thanks for jPlayer.  It's a spectacular tool and it's working flawlessly for me.  

I know this has been raised before in other places in the past, but what are your current thoughts on getting track lengths (durations) into jPlayerPlaylists (preferably pulled directly from the file)?  Is Flash the block here?  Alternatively, how about getting a hook into the playlist object array such that any given track lengths render in the player?  

I'm currently focusing on creating some skins for jPlayer that I'd like to give out to the community and features like these would be a _huge_ help in both my efforts and, I suppose, the adoption rate for jPlayer (and correspondingly interest in skins for jPlayer).

**Comment by eerlikh** [comment]
Can you please possibly go into more detail? How would I define it in the playlist file?
